(() => {
  'use strict';
  const LIVE_KEY = 'ravtext.liveRender';
  const PAUSE_KEY = 'ravtext.renderPaused';
  const PREV_LIVE_KEY = 'ravtext.renderPaused.prevLiveRender';
  const STOP_GUARD_MS = 15000;
  const text = {
    render: 'Render', stop: 'Stop render', pause: 'Pause render', resume: 'Resume render', resumeRender: 'Resume and render',
    paused: 'Render paused. You can change several settings without waiting.',
    pending: 'Render paused. Changes were saved but not rendered yet.',
    active: 'Render active.', stopped: 'Render stopped. Previous preview was kept.'
  };
  const state = { installed:false, paused:false, pending:false, running:false, stoppedUntil:0, snapshotHtml:null, snapshotScrollTop:0 };
  const byId = (id) => document.getElementById(id);
  const pages = () => byId('pages-container') || document.querySelector('.pages-container');
  const renderButton = () => byId('btn-render');
  const pauseButton = () => byId('btn-render-pause');
  const esc = (v) => String(v == null ? '' : v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
  function setStatus(v){ const el=byId('status'); if(el) el.textContent=v; }
  function liveEnabled(){ const v=localStorage.getItem(LIVE_KEY); return v===null ? true : v==='1'; }
  function setLiveEnabled(on){ localStorage.setItem(LIVE_KEY,on?'1':'0'); const cb=byId('live-render-toggle'); if(cb) cb.checked=!!on; }
  function snapshotPreview(){ const el=pages(); if(!el)return; state.snapshotHtml=el.innerHTML; state.snapshotScrollTop=el.scrollTop||0; }
  function restorePreview(){ const el=pages(); if(!el||state.snapshotHtml==null)return; el.innerHTML=state.snapshotHtml; el.scrollTop=state.snapshotScrollTop||0; }
  function addStyle(){ if(byId('ravtext-render-controls-style'))return; const s=document.createElement('style'); s.id='ravtext-render-controls-style'; s.textContent=`#btn-render.render-running{background:#b91c1c!important;color:#fff!important;border-color:#991b1b!important;animation:rtpulse .8s ease-in-out infinite}@keyframes rtpulse{0%,100%{opacity:1;transform:scale(1)}50%{opacity:.72;transform:scale(1.03)}}.btn-render-pause{margin-inline-start:6px;white-space:nowrap}.btn-render-pause.active{background:#f59e0b!important;color:#111827!important;border-color:#d97706!important;font-weight:700}.rt-help-backdrop{position:fixed;inset:0;z-index:9998;background:rgba(15,23,42,.55);display:flex;align-items:center;justify-content:center}.rt-help-modal{direction:rtl;width:700px;max-width:92vw;max-height:88vh;overflow:auto;background:#fff;border-radius:14px;box-shadow:0 12px 34px rgba(15,23,42,.24);padding:22px 24px;font-family:Segoe UI,system-ui,sans-serif;color:#0f172a}.rt-help-card{border:1px solid #dbeafe;border-radius:10px;padding:12px 14px;background:#f8fafc;margin-bottom:10px;line-height:1.65;color:#1f2937;font-size:14px}`; document.head.appendChild(s); }
  function ensurePauseButton(){ const r=renderButton(); if(!r||pauseButton())return; const b=document.createElement('button'); b.type='button'; b.id='btn-render-pause'; b.className='btn-render-pause'; b.textContent=text.pause; b.title=text.pause; r.insertAdjacentElement('afterend',b); }
  function paint(){ const r=renderButton(); const p=pauseButton(); if(r){r.classList.toggle('render-running',state.running); r.setAttribute('aria-busy',state.running?'true':'false'); r.textContent=state.running?text.stop:text.render; r.title=r.textContent;} if(p){p.classList.toggle('active',state.paused); p.setAttribute('aria-pressed',state.paused?'true':'false'); p.textContent=state.paused?(state.pending?text.resumeRender:text.resume):text.pause;} document.body.classList.toggle('render-paused',state.paused); document.body.classList.toggle('render-running',state.running); }
  function pauseRender(){ if(state.paused)return; localStorage.setItem(PREV_LIVE_KEY,liveEnabled()?'1':'0'); localStorage.setItem(PAUSE_KEY,'1'); state.paused=true; state.pending=false; setLiveEnabled(false); setStatus(text.paused); paint(); }
  function resumeRender(){ if(!state.paused)return; const prev=localStorage.getItem(PREV_LIVE_KEY); localStorage.removeItem(PAUSE_KEY); localStorage.removeItem(PREV_LIVE_KEY); state.paused=false; setLiveEnabled(prev==='0'?false:true); const should=state.pending; state.pending=false; paint(); if(should&&typeof window.__ravtextRerender==='function') window.__ravtextRerender(); else setStatus(text.active); }
  function stopRender(){ try{window.__ravtextCancelRender?.('toolbar');}catch(_){} state.running=false; state.stoppedUntil=Date.now()+STOP_GUARD_MS; restorePreview(); setStatus(text.stopped); paint(); }
  function markPending(ev){ if(!state.paused)return; const t=ev.target; if(!t?.closest)return; if(!t.closest('#panes-container,.ProseMirror,.pane,.toolbar,.ribbon-toolbar,.ribbon-panel'))return; state.pending=true; setStatus(text.pending); paint(); }
  async function openHelp(){ byId('rt-help-modal')?.remove(); let items=[['Overlapping text','Try rendering again.'],['Changes during render','Pause or stop render before changing many settings.']]; try{ const res=await fetch('/api/bug-reports/public?limit=500',{credentials:'same-origin',headers:{Accept:'application/json'}}); if(res.ok){ const data=await res.json(); const managed=(data?.items||[]).filter(x=>['troubleshooting','solutions'].includes(String(x?.status||'').trim())).map(x=>[String(x?.title||'').trim(),String(x?.body||'').trim()]).filter(x=>x[0]&&x[1]); if(managed.length) items=managed; }}catch(_){} const b=document.createElement('div'); b.id='rt-help-modal'; b.className='rt-help-backdrop'; b.innerHTML=`<div class="rt-help-modal"><button type="button" style="float:left" data-close>×</button><h2>Help</h2>${items.map(([a,c])=>`<div class="rt-help-card"><b>${esc(a)}:</b> ${esc(c)}</div>`).join('')}</div>`; b.addEventListener('click',ev=>{if(ev.target===b||ev.target.closest('[data-close]')) b.remove();}); document.body.appendChild(b); }
  function ensureTroubleshootingHeaderButton(){ const actions=document.querySelector('.app-header .app-header-actions')||document.querySelector('.app-header-actions'); if(!actions)return; let btn=byId('btn-troubleshooting'); if(!btn){btn=document.createElement('button'); btn.type='button'; btn.id='btn-troubleshooting'; btn.className='header-action-btn header-action-btn-icon'; btn.title='Help'; btn.innerHTML='<span class="header-action-icon">Help</span>'; const dev=byId('btn-dev-updates'); if(dev&&dev.parentNode===actions)dev.after(btn); else actions.insertBefore(btn,actions.firstElementChild||null);} if(btn.dataset.troubleshootingBootstrap!=='1'){btn.dataset.troubleshootingBootstrap='1'; btn.addEventListener('click',ev=>{ev.preventDefault();ev.stopImmediatePropagation();openHelp();});} }
  function wireButtons(){ ensurePauseButton(); ensureTroubleshootingHeaderButton(); const r=renderButton(); const p=pauseButton(); if(r&&r.dataset.renderPauseStopHook!=='1'){r.dataset.renderPauseStopHook='1'; r.addEventListener('click',ev=>{ if(state.running){ev.preventDefault();ev.stopImmediatePropagation();stopRender();return;} snapshotPreview(); state.running=true; state.stoppedUntil=0; paint();},true);} if(p&&p.dataset.renderPauseStopHook!=='1'){p.dataset.renderPauseStopHook='1'; p.addEventListener('click',ev=>{ev.preventDefault();ev.stopPropagation();state.paused?resumeRender():pauseRender();});} paint(); }
  function loadAddons(){ const src='/render-safety-addons.js'; if(document.querySelector(`script[src="${src}"]`))return; const s=document.createElement('script'); s.src=src; s.defer=true; s.dataset.ravtextRenderSafetyAddon='1'; document.head.appendChild(s); }
  function install(){ if(state.installed)return; state.installed=true; state.paused=localStorage.getItem(PAUSE_KEY)==='1'; if(state.paused)setLiveEnabled(false); addStyle(); wireButtons(); loadAddons(); document.addEventListener('input',markPending,true); document.addEventListener('change',markPending,true); document.addEventListener('paste',markPending,true); window.addEventListener('ravtext:engine-rendered',()=>{ if(Date.now()<state.stoppedUntil){restorePreview();setStatus(text.stopped);} state.running=false; paint(); }); let count=0; const retry=()=>{wireButtons();loadAddons();if(++count<36)setTimeout(retry,250);}; setTimeout(retry,250); }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true}); else setTimeout(install,0);
})();
