import app from './index_tidio.js';
import { getUserFromRequest } from './session.js';
const GAS='/api/ai-tools/gas',LOGS='/api/admin/ai-error-logs';
const rid=()=>{try{return crypto.randomUUID()}catch(_){return 'ai-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8)}};
const sec=()=>Math.floor(Date.now()/1000);
function cut(s,n=1400){s=s==null?'':String(s);return s.length>n?s.slice(0,n)+'...[truncated '+(s.length-n)+']':s}
function red(s,n=1400){return cut(String(s??'')
.replace(/(key=)([^&\s"'<>]+)/gi,'$1[redacted]')
.replace(/(api[_-]?key["']?\s*[:=]\s*["']?)([^"',\s}]+)/gi,'$1[redacted]')
.replace(/(access[_-]?code["']?\s*[:=]\s*["']?)([^"',\s}]+)/gi,'$1[redacted]')
.replace(/(authorization["']?\s*[:=]\s*["']?bearer\s+)([^"',\s}]+)/gi,'$1[redacted]')
.replace(/AIza[0-9A-Za-z_\-]{20,}/g,'[redacted-google-key]')
.replace(/sk-ant-[0-9A-Za-z_\-]{20,}/g,'[redacted-anthropic-key]')
.replace(/sk_[0-9A-Za-z_\-]{20,}/g,'[redacted-elevenlabs-key]')
.replace(/Bearer\s+[0-9A-Za-z._\-]{20,}/gi,'Bearer [redacted]'),n)}
function safe(v,d=0){if(v==null||typeof v==='number'||typeof v==='boolean')return v;if(typeof v==='string')return red(v);if(d>4)return '[deep]';if(Array.isArray(v))return v.slice(0,12).map(x=>safe(x,d+1));const o={};for(const[k,x]of Object.entries(v)){if(/api[_-]?key|access[_-]?code|token|secret|password|authorization/i.test(k))o[k]=x?'[redacted '+String(x).length+' chars]':'';else if(/content[_-]?base64|base64|text|custom_prompt|blob/i.test(k))o[k]=x?'[omitted '+String(x).length+' chars]':'';else if(k==='files'||k==='ocr_examples')o[k]=Array.isArray(x)?'[omitted array '+x.length+']':'[omitted]';else o[k]=safe(x,d+1)}return o}
function parse(t){try{return{ok:true,data:JSON.parse(t||'{}')}}catch(e){return{ok:false,error:e?.message||String(e)}}}
function provider(b){const p=String(b?.prompt_type||''),m=String(b?.model||'').toLowerCase();if(p==='elevenlabs_transcribe'||m.startsWith('elevenlabs'))return'elevenlabs';if(m.startsWith('gemini'))return'gemini';if(m.startsWith('claude'))return'claude';return m?m.split('-')[0]:'unknown'}
function sum(b){return{prompt_type:b?.prompt_type||null,provider:provider(b),model:b?.model||null,use_premium:b?.use_premium===true,has_api_key:!!b?.api_key,api_key_chars:b?.api_key?String(b.api_key).length:0,has_access_code:!!b?.access_code,access_code_chars:b?.access_code?String(b.access_code).length:0,files_count:Array.isArray(b?.files)?b.files.length:0,text_chars:b?.text?String(b.text).length:0,custom_prompt_chars:b?.custom_prompt?String(b.custom_prompt).length:0,engines_used:Array.isArray(b?.engines_used)?b.engines_used:undefined,preferred_engine:b?.preferred_engine||undefined,language_code:b?.language_code||undefined}}
function st(data,fb=500){const s=((data?.error||'')+' '+(data?.message||'')).toLowerCase();if(/invalid_api_key|invalid api key|unauthorized|permission_denied/.test(s))return 401;if(/forbidden/.test(s))return 403;if(/quota|rate limit|resource_exhausted/.test(s))return 429;if(/bad_request|missing|invalid_json/.test(s))return 400;if(/too large|413/.test(s))return 413;if(/timeout|deadline/.test(s))return 504;if(/proxy_fetch_failed/.test(s))return 502;return fb}
function cause(status,data,r){const s=((data?.error||'')+' '+(data?.message||'')).toLowerCase();if(!r.has_api_key&&!r.has_access_code)return'missing_user_api_key_or_access_code';if(/invalid_api_key|invalid api key/.test(s)||status===401||status===403)return'provider_rejected_user_api_key_or_wrong_provider';if(/quota|rate limit|resource_exhausted/.test(s)||status===429)return'provider_quota_or_rate_limit';if(status===413)return'request_too_large';if(status===504)return'timeout';if(status>=500)return'server_or_proxy_error';return'unclassified_ai_error'}
function msg(d){return['Detailed AI error log','debug_id='+d.debug_id,'time='+d.time,'stage='+d.stage,'http_status='+d.http_status,'upstream_http_status='+(d.upstream_http_status??'none'),'duration_ms='+d.duration_ms,'provider='+d.request.provider,'model='+(d.request.model||'none'),'prompt_type='+(d.request.prompt_type||'none'),'has_api_key='+d.request.has_api_key,'api_key_chars='+d.request.api_key_chars,'has_access_code='+d.request.has_access_code,'files_count='+d.request.files_count,'text_chars='+d.request.text_chars,'possible_cause='+d.possible_cause,d.upstream_error?'upstream_error='+d.upstream_error:'',d.upstream_message?'upstream_message='+red(d.upstream_message,800):'',d.preview?'response_preview='+red(d.preview,1000):''].filter(Boolean).join('\n')}
async function ensure(env){if(!env?.DB)return false;await env.DB.prepare(`CREATE TABLE IF NOT EXISTS ai_error_logs(id INTEGER PRIMARY KEY AUTOINCREMENT,debug_id TEXT NOT NULL,created_at INTEGER NOT NULL,level TEXT NOT NULL,status INTEGER,provider TEXT,model TEXT,prompt_type TEXT,possible_cause TEXT,message TEXT,details_json TEXT)`).run();await env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_ai_error_logs_debug ON ai_error_logs(debug_id)').run();await env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_ai_error_logs_time ON ai_error_logs(created_at)').run();return true}
async function save(env,d,level='error'){try{if(!(await ensure(env)))return;await env.DB.prepare(`INSERT INTO ai_error_logs(debug_id,created_at,level,status,provider,model,prompt_type,possible_cause,message,details_json) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(d.debug_id,sec(),level,d.http_status||null,d.request.provider||null,d.request.model||null,d.request.prompt_type||null,d.possible_cause||null,msg(d),JSON.stringify(safe(d))).run()}catch(e){try{console.warn('[ai-debug] persist_failed',e?.message||e)}catch(_){}}}
function headers(res,id){const h=new Headers(res?.headers||{});h.delete('content-length');h.set('cache-control','no-store');h.set('x-ravtext-debug-id',id);return h}
async function detailed(env,d,payload=null,status=null,h=null){d.http_status=status||d.http_status||500;d.possible_cause=d.possible_cause||cause(d.http_status,payload,d.request);try{(d.http_status===429?console.warn:console.error)('[ai-debug] '+JSON.stringify(safe(d)))}catch(_){}await save(env,d,d.http_status===429?'warn':'error');const out=payload&&typeof payload==='object'?{...payload}:{ };out.original_error=out.error||out.original_error;out.error='ai_tool_detailed_error';out.message=msg(d);out.debug_id=d.debug_id;out.error_details=safe(d);return Response.json(out,{status:d.http_status,headers:h||{'cache-control':'no-store','x-ravtext-debug-id':d.debug_id}})}
async function adminLogs(req,env,url){const u=await getUserFromRequest(req,env);if(!u)return Response.json({error:'not_logged_in'},{status:401});if(!u.is_admin)return Response.json({error:'forbidden'},{status:403});await ensure(env);const limit=Math.max(1,Math.min(200,Number(url.searchParams.get('limit'))||50)),id=(url.searchParams.get('debug_id')||'').trim();const r=id?await env.DB.prepare('SELECT * FROM ai_error_logs WHERE debug_id=? ORDER BY id DESC LIMIT ?').bind(id,limit).all():await env.DB.prepare('SELECT * FROM ai_error_logs ORDER BY id DESC LIMIT ?').bind(limit).all();return Response.json({logs:r?.results||[],limit,debug_id:id||null},{headers:{'cache-control':'no-store'}})}
async function gas(req,env,ctx,url){const id=rid(),start=Date.now();let raw='',body={},perr=null;try{raw=await req.clone().text();const p=parse(raw);if(p.ok&&p.data&&typeof p.data==='object')body=p.data;else perr=p.error}catch(e){perr=e?.message||String(e)}const r=sum(body);const base={debug_id:id,time:new Date().toISOString(),method:req.method,path:url.pathname,stage:'before_worker',request:r,request_parse_error:perr||undefined};try{console.log('[ai-debug] start '+JSON.stringify(safe(base)))}catch(_){}
if(req.method==='POST'&&!perr&&!r.has_api_key&&!r.has_access_code){const d={...base,stage:'pre_validation',upstream_http_status:null,http_status:400,duration_ms:Date.now()-start,upstream_error:'missing_user_api_key_or_access_code',upstream_message:'Request did not include api_key or access_code.',possible_cause:'missing_user_api_key_or_access_code'};return detailed(env,d,{error:'missing_user_api_key',message:d.upstream_message},400)}
let res;try{res=await app.fetch(req,env,ctx)}catch(e){const d={...base,stage:'worker_exception',upstream_http_status:null,http_status:500,duration_ms:Date.now()-start,exception_name:e?.name||'Error',exception_message:red(e?.message||String(e),800),stack:red(e?.stack||'',1200),possible_cause:'unhandled_worker_exception'};return detailed(env,d,{error:'worker_exception',message:d.exception_message},500)}
const text=await res.text(),p=parse(text),payload=p.ok&&p.data&&typeof p.data==='object'?p.data:null,per=!!payload?.error;if(res.ok&&p.ok&&!per){try{console.log('[ai-debug] ok '+JSON.stringify({debug_id:id,status:res.status,duration_ms:Date.now()-start,provider:r.provider,model:r.model,prompt_type:r.prompt_type}))}catch(_){}return new Response(text,{status:res.status,statusText:res.statusText,headers:headers(res,id)})}
const eff=per&&res.status>=200&&res.status<300?st(payload,500):(res.status||500);const d={...base,stage:p.ok?'worker_or_provider_error':'non_json_error',upstream_http_status:res.status||null,http_status:eff,duration_ms:Date.now()-start,upstream_error:payload?.error||(p.ok?null:'non_json_response'),upstream_message:payload?.message||null,response_chars:text.length,preview:p.ok?red(JSON.stringify(safe(payload??p.data)),1200):red(text,1200),possible_cause:cause(eff,payload,r)};return detailed(env,d,payload,eff,headers(res,id))}
export default{async fetch(req,env,ctx){const url=new URL(req.url);if(url.pathname===LOGS)return adminLogs(req,env,url);if(url.pathname===GAS)return gas(req,env,ctx,url);return app.fetch(req,env,ctx)},async scheduled(event,env,ctx){if(typeof app.scheduled==='function')return app.scheduled(event,env,ctx)}};
