const BTN_ID="nested-notes-open-stream-menu-btn";
const POP_ID="nested-notes-stream-menu-popover";
const INPUT_ID="talmud-streams-input";
const MAX=2;
let installed=false;
function $(id){return document.getElementById(id)}
function all(s){return Array.from(document.querySelectorAll(s))}
function text(el){return [el?.textContent,el?.value,el?.title,el?.getAttribute?.("aria-label"),el?.id].filter(Boolean).join(" ")}
function vis(el){if(!(el instanceof HTMLElement)||!el.isConnected)return false;const s=getComputedStyle(el);if(s.display==="none"||s.visibility==="hidden"||Number(s.opacity)===0)return false;const r=el.getBoundingClientRect();return r.width>0&&r.height>0}
function anchor(){return all("button,[role='button'],input[type='button'],input[type='submit'],label").find(el=>{if(!(el instanceof HTMLElement)||el.id===BTN_ID||!vis(el))return false;const t=text(el);return t.includes("הערות להערות")||/הצג.*הערות.*להערות/.test(t)||/תמיכה.*הערות.*להערות/.test(t)})||$("talmud-stream-picker")||$("talmud-add-stream-btn")||$(INPUT_ID)}
function selected(){const i=$(INPUT_ID);return i?(i.value.match(/\d{2}/g)||[]):[]}
function codes(){const s=new Set();all(".stream[data-stream],[data-stream]").forEach(el=>{const c=el.getAttribute("data-stream");if(/^\d{2}$/.test(c||""))s.add(c)});if(!s.size)for(let i=1;i<=10;i++)s.add(String(i).padStart(2,"0"));return Array.from(s).sort()}
function setSelected(list){const i=$(INPUT_ID);if(!i)return;i.value=list.slice(0,MAX).sort().join(",");i.dispatchEvent(new Event("change",{bubbles:true}));i.dispatchEvent(new Event("input",{bubbles:true}))}
function open(){const p=$(POP_ID);return !!p&&p.style.display!=="none"}
function button(){let b=$(BTN_ID);if(!b){b=document.createElement("button");b.id=BTN_ID;b.type="button";b.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();toggle()});document.body.appendChild(b)}
b.innerHTML='<span aria-hidden="true">🌊</span><span>פתח תפריט זרמים</span>';
b.setAttribute("aria-label","פתח תפריט זרמים");b.setAttribute("aria-haspopup","dialog");b.setAttribute("aria-expanded",open()?"true":"false");
b.style.cssText="position:fixed;z-index:10020;display:inline-flex;align-items:center;gap:5px;padding:4px 10px;border-radius:999px;border:1px solid rgba(44,90,160,.38);background:linear-gradient(180deg,rgba(44,90,160,.13),rgba(44,90,160,.06));color:inherit;font:inherit;font-size:12px;font-weight:600;line-height:1.35;cursor:pointer;white-space:nowrap;box-shadow:0 1px 3px rgba(0,0,0,.12);pointer-events:auto";
place();return b}
function place(){const b=$(BTN_ID);if(!b)return;const a=anchor();let top=88,right=12,pad=10;if(a instanceof HTMLElement&&vis(a)){const r=a.getBoundingClientRect();top=r.top+Math.max(0,(r.height-(b.offsetHeight||28))/2);right=Math.max(pad,window.innerWidth-r.left+6)}const w=b.offsetWidth||150,h=b.offsetHeight||28;top=Math.max(pad,Math.min(window.innerHeight-h-pad,top));right=Math.max(pad,Math.min(window.innerWidth-w-pad,right));b.style.top=Math.round(top)+"px";b.style.right=Math.round(right)+"px";b.style.left="auto"}
function pop(){let p=$(POP_ID);if(!p){p=document.createElement("div");p.id=POP_ID;p.dir="rtl";p.setAttribute("role","dialog");p.setAttribute("aria-label","תפריט זרמים");document.body.appendChild(p)}
p.style.cssText="position:fixed;z-index:10030;display:none;min-width:260px;max-width:min(360px,calc(100vw - 16px));max-height:min(62vh,420px);overflow:auto;box-sizing:border-box;padding:9px;border:1px solid rgba(0,0,0,.16);border-radius:12px;background:var(--rt-surface,#fff);color:var(--rt-text,#222);box-shadow:0 10px 28px rgba(0,0,0,.20);font-size:12px;pointer-events:auto";return p}
function render(){const p=pop();p.innerHTML="";const head=document.createElement("div");head.style.cssText="display:flex;align-items:center;gap:6px;margin-bottom:7px";const title=document.createElement("strong");title.textContent="🌊 תפריט זרמים";const sp=document.createElement("span");sp.style.flex="1";const x=document.createElement("button");x.type="button";x.textContent="×";x.title="סגור";x.style.cssText="border:0;background:transparent;font-size:18px;line-height:1;cursor:pointer;color:inherit;padding:0 2px";x.addEventListener("click",close);head.append(title,sp,x);p.appendChild(head);
const inp=$(INPUT_ID);const hint=document.createElement("div");hint.textContent=inp?`בחר עד ${MAX} זרמים להצגה בחלוניות.`:"בקר הזרמים עדיין לא נטען במסך הזה.";hint.style.cssText="opacity:.72;margin:0 0 8px;font-size:11px";p.appendChild(hint);
if(inp){const cur=selected(),wrap=document.createElement("div");wrap.style.cssText="display:flex;flex-wrap:wrap;gap:5px;margin-bottom:8px";codes().forEach(code=>{const on=cur.includes(code),c=document.createElement("button");c.type="button";c.textContent=on?`✓ ${code}`:code;c.style.cssText=`min-width:34px;padding:4px 8px;border-radius:999px;border:1px solid rgba(0,0,0,.12);${on?"background:var(--rt-accent,#2c5aa0);color:#fff":"background:rgba(0,0,0,.035);color:inherit"};font:inherit;font-size:12px;cursor:pointer`;c.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();const next=on?cur.filter(v=>v!==code):(cur.length>=MAX?[...cur.slice(1),code]:[...cur,code]);setSelected(next);render()});wrap.appendChild(c)});p.appendChild(wrap);const curLine=document.createElement("div");curLine.textContent=cur.length?`נבחרו: ${cur.join(", ")}`:"לא נבחרו זרמים";curLine.style.cssText="border-top:1px solid rgba(0,0,0,.10);padding-top:7px;opacity:.72;font-size:11px";p.appendChild(curLine)}
const h=document.createElement("div");h.textContent="@01 מזוהה אוטומטית • Tab בתוך @NN לקפיצה • הערה על הערה: @02 בתוך הערת @01";h.style.cssText="margin-top:8px;border:1px solid rgba(0,0,0,.10);border-radius:9px;padding:6px 7px;background:rgba(0,0,0,.025);font-size:11px;line-height:1.45;opacity:.8";p.appendChild(h)}
function pos(){const p=pop(),b=$(BTN_ID),r=b?.getBoundingClientRect?.(),pad=8;p.style.display="block";p.style.visibility="hidden";let top=r?r.bottom+8:pad,right=r?window.innerWidth-r.right:pad;const h=p.offsetHeight||260,w=p.offsetWidth||280;if(r&&top+h>window.innerHeight-pad)top=r.top-h-8;top=Math.max(pad,Math.min(window.innerHeight-h-pad,top));right=Math.max(pad,Math.min(window.innerWidth-w-pad,right));p.style.top=Math.round(top)+"px";p.style.right=Math.round(right)+"px";p.style.left="auto";p.style.visibility="visible"}
function show(){render();pos();$(BTN_ID)?.setAttribute("aria-expanded","true");document.addEventListener("keydown",key,true);window.addEventListener("resize",reposition);window.addEventListener("scroll",reposition,true)}
function close(){const p=$(POP_ID);if(p)p.style.display="none";$(BTN_ID)?.setAttribute("aria-expanded","false");document.removeEventListener("keydown",key,true);window.removeEventListener("resize",reposition);window.removeEventListener("scroll",reposition,true)}
function toggle(){open()?close():show()}
function key(e){if(e.key==="Escape")close()}
function reposition(){place();if(open())pos()}
export function installCompactStreamMenuButton(){if(installed||typeof document==="undefined")return;installed=true;const run=()=>button();if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",run,{once:true});else run();[0,300,1000,2500,5000].forEach(ms=>setTimeout(run,ms));window.addEventListener("resize",place);window.addEventListener("scroll",place,true)}
installCompactStreamMenuButton();
