const B="nested-notes-open-stream-menu-btn",P="nested-notes-stream-menu-popover",I="talmud-streams-input";let R=0;
const G=[["חלונית",["+ חלונית","✕ הסר חלונית","✂ פצל לחלוניות","✂ הפרד הערות","🔗 מזג / פרק","⤺ אחד"]],["תצוגה וכלים",["תצוגה","⚙ כלים","🔗 גלילה","▥ זרמים לרוחב","☷ שורות","↺ איפוס"]]];
const IDS={"+ חלונית":["talmud-add-stream-btn","add-pane-btn","add-pane"],"✕ הסר חלונית":["remove-pane-btn","delete-pane-btn"],"✂ פצל לחלוניות":["split-panes-btn","split-pane-btn"],"✂ הפרד הערות":["separate-notes-btn","split-notes-btn"],"🔗 מזג / פרק":["merge-unmerge-btn","merge-toggle-btn","unlink-notes-btn"],"⤺ אחד":["single-pane-btn","one-pane-btn","collapse-panes-btn"],"תצוגה":["view-menu-btn","display-menu-btn","layout-menu-btn"],"⚙ כלים":["tools-menu-btn","settings-menu-btn"],"🔗 גלילה":["scroll-sync-toggle","sync-scroll-toggle","linked-scroll-toggle"],"▥ זרמים לרוחב":["horizontal-streams-toggle","streams-horizontal-toggle","talmud-side-mode-select"],"☷ שורות":["talmud-crown-lines-input","crown-lines-input","rows-input"],"↺ איפוס":["reset-layout-btn","layout-reset-btn","reset-btn"]};
const W={"+ חלונית":["חלונית","חדש"],"✕ הסר חלונית":["הסר","חלונית"],"✂ פצל לחלוניות":["פצל","חלוניות"],"✂ הפרד הערות":["הפרד","הערות"],"🔗 מזג / פרק":["מזג"],"⤺ אחד":["אחד"],"תצוגה":["תצוגה"],"⚙ כלים":["כלים"],"🔗 גלילה":["גלילה"],"▥ זרמים לרוחב":["זרמים","לרוחב"],"☷ שורות":["שורות"],"↺ איפוס":["איפוס"]};
const $=i=>document.getElementById(i),Q=s=>[...document.querySelectorAll(s)];
function txt(e){return[e?.textContent,e?.value,e?.title,e?.getAttribute?.("aria-label"),e?.id].filter(Boolean).join(" ").replace(/\s+/g," ")}
function ok(e){try{if(!(e instanceof HTMLElement)||!e.isConnected)return 0;let s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!="none"&&s.visibility!="hidden"&&+s.opacity!==0&&r.width>0&&r.height>0}catch(_){return 1}}
function mine(e){return $(B)?.contains(e)||$(P)?.contains(e)}
function controls(){return Q("button,[role='button'],input[type='button'],input[type='submit'],input[type='checkbox'],input[type='radio'],select,label,summary,a[href]").filter(e=>ok(e)&&!mine(e))}
function anchor(){return controls().find(e=>/הערות להערות|הצג.*הערות|תמיכה.*הערות/.test(txt(e)))||$("talmud-stream-picker")||$("talmud-add-stream-btn")||$(I)}
function find(label){for(const id of IDS[label]||[]){let e=$(id);if(e&&ok(e)&&!mine(e))return e;let l=document.querySelector(`label[for="${id}"]`);if(l&&ok(l)&&!mine(l))return l}let w=W[label]||[];return controls().find(e=>w.every(x=>txt(e).includes(x)))}
function fire(e){if(!e)return 0;let t=e instanceof HTMLLabelElement&&e.control?e.control:e;if(t.disabled||t.getAttribute?.("aria-disabled")==="true")return 0;t.focus?.();t.click?.();t.dispatchEvent?.(new Event("input",{bubbles:true}));t.dispatchEvent?.(new Event("change",{bubbles:true}));return 1}
function open(){let p=$(P);return !!(p&&p.style.display!="none")}
function codes(){let s=new Set;Q(".stream[data-stream],[data-stream]").forEach(e=>{let c=e.getAttribute("data-stream");if(/^\d{2}$/.test(c||""))s.add(c)});if(!s.size)for(let i=1;i<=10;i++)s.add(String(i).padStart(2,"0"));return[...s].sort()}
function sel(){let i=$(I);return i?(i.value.match(/\d{2}/g)||[]):[]}
function setSel(a){let i=$(I);if(!i)return;i.value=a.slice(0,2).sort().join(",");i.dispatchEvent(new Event("change",{bubbles:true}));i.dispatchEvent(new Event("input",{bubbles:true}))}
function placeBtn(){let b=$(B);if(!b)return;let a=anchor(),top=88,right=12,p=10;if(a&&ok(a)){let r=a.getBoundingClientRect();top=r.top+Math.max(0,(r.height-(b.offsetHeight||28))/2);right=Math.max(p,innerWidth-r.left+6)}top=Math.max(p,Math.min(innerHeight-(b.offsetHeight||28)-p,top));right=Math.max(p,Math.min(innerWidth-(b.offsetWidth||150)-p,right));b.style.top=Math.round(top)+"px";b.style.right=Math.round(right)+"px";b.style.left="auto"}
function button(){let b=$(B);if(!b){b=document.createElement("button");b.id=B;b.type="button";b.onclick=e=>{e.preventDefault();e.stopPropagation();toggle()};document.body.appendChild(b)}b.innerHTML="<span>🌊</span><span>פתח תפריט זרמים</span>";b.setAttribute("aria-haspopup","dialog");b.setAttribute("aria-expanded",open()?"true":"false");b.style.cssText="position:fixed;z-index:10020;display:inline-flex;align-items:center;gap:5px;padding:4px 10px;border-radius:999px;border:1px solid rgba(44,90,160,.38);background:linear-gradient(180deg,rgba(44,90,160,.13),rgba(44,90,160,.06));color:inherit;font:inherit;font-size:12px;font-weight:600;line-height:1.35;cursor:pointer;white-space:nowrap;box-shadow:0 1px 3px rgba(0,0,0,.12);pointer-events:auto";placeBtn()}
function pop(){let p=$(P);if(!p){p=document.createElement("div");p.id=P;p.dir="rtl";p.setAttribute("role","dialog");document.body.appendChild(p)}p.style.cssText="position:fixed;z-index:10030;display:none;flex-direction:column;width:min(760px,calc(100vw - 16px));max-height:min(82vh,680px);overflow:hidden;border:1px solid rgba(0,0,0,.16);border-radius:14px;background:var(--rt-surface,#fff);color:var(--rt-text,#222);box-shadow:0 12px 32px rgba(0,0,0,.22);font-size:12px;pointer-events:auto;box-sizing:border-box";return p}
function closeBtn(t){let b=document.createElement("button");b.type="button";b.textContent=t;b.style.cssText="border:1px solid rgba(0,0,0,.14);border-radius:10px;background:rgba(0,0,0,.045);color:inherit;font:inherit;font-size:12px;font-weight:700;cursor:pointer;padding:7px 12px;min-height:32px";b.onclick=e=>{e.preventDefault();e.stopPropagation();close()};return b}
function title(t){let d=document.createElement("div");d.textContent=t;d.style.cssText="font-weight:700;font-size:12px;opacity:.78;margin:10px 0 6px";return d}
function msg(t){let m=$("stream-menu-status");if(m)m.textContent=t||""}
function action(label){let b=document.createElement("button");b.type="button";b.textContent=label;b.style.cssText="display:inline-flex;align-items:center;justify-content:center;min-height:31px;padding:6px 8px;border-radius:9px;border:1px solid rgba(0,0,0,.12);background:rgba(0,0,0,.035);color:inherit;font:inherit;font-size:12px;cursor:pointer;white-space:nowrap";b.onclick=e=>{e.preventDefault();e.stopPropagation();fire(find(label))?(msg(`בוצע: ${label}`),setTimeout(render,120)):msg(`לא נמצא כרגע בקר פעיל עבור: ${label}`)};return b}
function grid(){let g=document.createElement("div");g.style.cssText="display:grid;grid-template-columns:repeat(auto-fit,minmax(118px,1fr));gap:6px";return g}
function render(){let p=pop();p.innerHTML="";let head=document.createElement("div");head.style.cssText="flex:0 0 auto;display:flex;align-items:center;gap:8px;padding:10px 12px;border-bottom:1px solid rgba(0,0,0,.10);background:var(--rt-surface,#fff)";head.innerHTML="<strong style='font-size:13px'>🌊 תפריט זרמים</strong><span style='flex:1'></span>";head.appendChild(closeBtn("× סגור"));let body=document.createElement("div");body.style.cssText="flex:1 1 auto;min-height:0;overflow-y:auto;overflow-x:hidden;overscroll-behavior:contain;-webkit-overflow-scrolling:touch;touch-action:pan-y;padding:10px 12px 12px;scrollbar-gutter:stable";body.addEventListener("wheel",e=>e.stopPropagation(),{passive:true});body.addEventListener("touchmove",e=>e.stopPropagation(),{passive:true});G.forEach(g=>{body.appendChild(title(g[0]));let gr=grid();g[1].forEach(x=>gr.appendChild(action(x)));body.appendChild(gr)});body.appendChild(title("זרמים"));let i=$(I),h=document.createElement("div");h.textContent=i?"בחר עד 2 זרמים להצגה בחלוניות.":"בקר הזרמים עדיין לא נטען במסך הזה.";h.style.cssText="opacity:.72;margin:0 0 8px;font-size:11px";body.appendChild(h);if(i){let cur=sel(),w=document.createElement("div");w.style.cssText="display:flex;flex-wrap:wrap;gap:6px;margin-bottom:8px";codes().forEach(c=>{let on=cur.includes(c),x=document.createElement("button");x.type="button";x.textContent=on?`✓ ${c}`:c;x.style.cssText=`min-width:38px;padding:5px 9px;border-radius:999px;border:1px solid rgba(0,0,0,.12);${on?"background:var(--rt-accent,#2c5aa0);color:#fff":"background:rgba(0,0,0,.035);color:inherit"};font:inherit;font-size:12px;cursor:pointer`;x.onclick=e=>{e.preventDefault();e.stopPropagation();setSel(on?cur.filter(v=>v!==c):(cur.length>=2?[...cur.slice(1),c]:[...cur,c]));render()};w.appendChild(x)});body.appendChild(w)}body.appendChild(title("זיהוי וקיצורים"));let help=document.createElement("div");help.textContent="@01 בכל מקום מזוהה אוטומטית • Tab בתוך @NN לקפיצה • הערה על הערה: @02 בתוך הערת @01";help.style.cssText="border:1px solid rgba(0,0,0,.10);border-radius:10px;padding:7px 8px;background:rgba(0,0,0,.025);font-size:11px;line-height:1.45;opacity:.82";body.appendChild(help);let st=document.createElement("div");st.id="stream-menu-status";st.style.cssText="margin-top:9px;opacity:.74;font-size:11px;min-height:1.4em";body.appendChild(st);let foot=document.createElement("div");foot.style.cssText="flex:0 0 auto;display:flex;justify-content:flex-start;padding:9px 12px;border-top:1px solid rgba(0,0,0,.10);background:var(--rt-surface,#fff)";foot.appendChild(closeBtn("סגור תפריט"));p.append(head,body,foot)}
function pos(){let p=pop(),b=$(B),r=b?.getBoundingClientRect?.(),pad=8;p.style.display="flex";p.style.visibility="hidden";let h=p.offsetHeight||520,w=p.offsetWidth||720,top=r?r.bottom+8:pad,right=r?innerWidth-r.right:pad;if(r&&top+h>innerHeight-pad)top=r.top-h-8;top=Math.max(pad,Math.min(innerHeight-h-pad,top));right=Math.max(pad,Math.min(innerWidth-w-pad,right));p.style.top=Math.round(top)+"px";p.style.right=Math.round(right)+"px";p.style.left="auto";p.style.visibility="visible"}
function show(){render();pos();$(B)?.setAttribute("aria-expanded","true");document.addEventListener("keydown",key,true);addEventListener("resize",repos)}
function close(){let p=$(P);if(p)p.style.display="none";$(B)?.setAttribute("aria-expanded","false");document.removeEventListener("keydown",key,true);removeEventListener("resize",repos)}
function toggle(){open()?close():show()}
function key(e){if(e.key==="Escape")close()}
function repos(){placeBtn();if(open())pos()}
export function installCompactStreamMenuButton(){if(R||typeof document==="undefined")return;R=1;let run=()=>button();document.readyState==="loading"?document.addEventListener("DOMContentLoaded",run,{once:true}):run();[0,300,1000,2500,5000].forEach(ms=>setTimeout(run,ms));addEventListener("resize",placeBtn);addEventListener("scroll",placeBtn,true)}
installCompactStreamMenuButton();
