const M="nested-notes-open-stream-menu-btn",H="nested-notes-short-help-btn",W="nested-notes-stream-menu-actions-wrap",P="nested-notes-stream-menu-popover",B="stream-menu-bulk-actions",S="stream-menu-actions-style",T="nested-notes-toggle";
let I=0;
const $=i=>document.getElementById(i);
const HELP="איך מקשרים הערות לפנים — בקצרה:\n\n1. בטקסט הראשי כותבים סימן זרם, למשל @01.\n2. בחלון זרם 01 כותבים את ההערות לפי הסדר.\n3. ה-@01 הראשון מתחבר להערה הראשונה, השני לשנייה.\n4. הערה בתוך הערה מסמנים בסימן אחר, למשל @02.\n5. אחרי שינוי לוחצים רנדר.";
function pm(){return window.paneManager}
function render(){try{window.__ravtextApplyPaneWidths?.()}catch(_){}try{window.__ravtextRerender?.()}catch(_){}}
function st(t){const e=$("stream-menu-status");if(e)e.textContent=t||""}
function panes(){const m=pm();return Array.isArray(m?.panes)?m.panes:[]}
function streamPanes(){return panes().filter(p=>p?.streamCode)}
function del(){const m=pm(),all=panes(),ss=streamPanes();if(!m||!all.length)return alert("לא נמצאו חלונות זרמים."),0;if(!ss.length)return alert("אין כרגע חלונות זרמים למחיקה."),0;if(!confirm("אתה בטוח? פעולה זו תמחק את כל חלונות הזרמים ותשאיר רק את הזרם הראשי."))return 0;ss.slice().forEach(p=>{try{typeof m.removePane=="function"?m.removePane(p.id):(p.element?.remove(),m.panes=m.panes.filter(x=>x!==p))}catch(e){console.warn("[stream-menu-full] remove failed",e)}});try{m.merged=false;m._save?.({immediate:true});m._emit?.("change")}catch(_){}render();st(`נמחקו ${ss.length} חלונות זרמים. הזרם הראשי נשאר.`);return 1}
function clearAll(){const m=pm(),all=panes();if(!m||!all.length)return alert("לא נמצאו חלונות לניקוי."),0;if(!confirm("אתה בטוח? פעולה זו תנקה את כל תוכן החלונות. החלונות עצמם יישארו."))return 0;let n=0;all.forEach(p=>{try{p.editor?.commands?.clearContent?p.editor.commands.clearContent(true):p.editor?.commands?.setContent?.({type:"doc",content:[{type:"paragraph"}]});p.scheduleMarkerBarUpdate?.({immediate:true});n++}catch(e){console.warn("[stream-menu-full] clear failed",e)}});try{m._save?.({immediate:true});m._emit?.("change")}catch(_){}render();st(`נוקה תוכן ${n} חלונות. החלונות נשארו.`);return 1}
function run(c){if(c=="del")return del();if(c=="clear")return clearAll();if(c=="help")return alert(HELP),1}
function btn(t,c,d=0){let b=document.createElement("button");b.type="button";b.textContent=t;b.style.cssText=`min-height:28px;padding:4px 9px;border-radius:8px;border:1px solid ${d?"rgba(170,40,40,.28)":"rgba(0,0,0,.14)"};background:${d?"rgba(170,40,40,.055)":"rgba(0,0,0,.035)"};color:inherit;font:inherit;font-size:12px;cursor:pointer;white-space:nowrap`;b.onclick=e=>{e.preventDefault();e.stopPropagation();run(c)};return b}
function pop(){const p=$(P);if(!p||p.style.display=="none")return;const body=p.children[1]||p;if(body.querySelector("#"+B))return;const box=document.createElement("div");box.id=B;box.dir="rtl";box.style.cssText="border:1px solid rgba(170,40,40,.18);border-radius:10px;background:rgba(170,40,40,.025);padding:8px;margin:0 0 10px";const title=document.createElement("div");title.textContent="פעולות ניקוי";title.style.cssText="font-weight:700;font-size:12px;margin:0 0 6px;opacity:.82";const grid=document.createElement("div");grid.style.cssText="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:6px";grid.append(btn("מחק את כל חלונות הזרמים","del",1),btn("נקה את כל תוכן החלונות","clear",1));box.append(title,grid);body.prepend(box)}
function css(){if($(S))return;let s=document.createElement("style");s.id=S;s.textContent=`#${W}{display:inline-flex;align-items:center;gap:6px;margin-inline-start:6px;vertical-align:middle;position:static!important;z-index:auto!important;pointer-events:auto!important}#${W} #${M},#${W} #${H}{position:static!important;right:auto!important;left:auto!important;top:auto!important;bottom:auto!important;transform:none!important;margin:0!important;vertical-align:middle!important;z-index:auto!important;pointer-events:auto!important}`;document.head.appendChild(s)}
function reset(b){b.hidden=false;b.style.position="static";b.style.zIndex="auto";b.style.top="auto";b.style.right="auto";b.style.left="auto";b.style.bottom="auto";b.style.transform="none";b.style.margin="0";b.style.pointerEvents="auto"}
function help(){let b=$(H);if(!b){b=document.createElement("button");b.id=H;b.type="button";b.onclick=e=>{e.preventDefault();e.stopPropagation();run("help")}}b.textContent="הסבר קצר";b.title="הסבר קצר על קישור ההערות לפנים";b.style.cssText="display:inline-flex;align-items:center;justify-content:center;gap:5px;min-height:28px;padding:4px 10px;border-radius:999px;border:1px solid rgba(44,90,160,.38);background:linear-gradient(180deg,rgba(44,90,160,.13),rgba(44,90,160,.06));color:inherit;font:inherit;font-size:12px;font-weight:600;line-height:1.35;cursor:pointer;white-space:nowrap;box-shadow:0 1px 3px rgba(0,0,0,.12);pointer-events:auto;position:static;z-index:auto";return b}
function anchor(){const t=$(T);if(!t)return null;return t.closest("label")||t.closest(".tb-group,.settings-row,.setting-row,.control-row,.field-row,.form-row")||t.parentElement||t}
function fallback(){return document.querySelector(".source-stream-toolbar")||document.querySelector(".panes-toolbar")||document.querySelector("#settings-panel")||document.querySelector("#settings-pane")||document.body}
function place(w,a){const h=a?.parentElement||fallback();if(!a||!h){if(!w.isConnected)document.body.appendChild(w);return}if(a.matches?.(".source-stream-toolbar,.panes-toolbar")){if(!a.contains(w))a.appendChild(w);return}if(w.parentElement!==h||w.previousElementSibling!==a)a.insertAdjacentElement("afterend",w)}
function align(){css();const m=$(M);if(!m)return;let w=$(W);if(!w){w=document.createElement("span");w.id=W;w.dir="rtl"}place(w,anchor());w.hidden=false;w.style.cssText="display:inline-flex;align-items:center;gap:6px;margin-inline-start:6px;vertical-align:middle;position:static;z-index:auto;pointer-events:auto";if(!w.contains(m))w.prepend(m);reset(m);const hb=help();if(!w.contains(hb))w.appendChild(hb);reset(hb);m.setAttribute("aria-describedby",H)}
function toolbar(){const t=document.querySelector(".panes-toolbar");if(!t)return;let d=$("pane-delete-streams-btn"),c=$("pane-clear-all-content-btn");if(!d){d=btn("מחק את כל חלונות הזרמים","del");d.id="pane-delete-streams-btn"}if(!c){c=btn("נקה את כל תוכן החלונות","clear");c.id="pane-clear-all-content-btn"}if(!t.contains(d))t.appendChild(d);if(!t.contains(c))t.appendChild(c)}
function apply(){align();toolbar();pop()}
export function installCompactStreamMenuFullPatch(){if(I||typeof document=="undefined")return;I=1;const start=()=>{apply();const o=new MutationObserver(()=>{clearTimeout(o._t);o._t=setTimeout(apply,60)});o.observe(document.body,{childList:true,subtree:true})};document.readyState=="loading"?document.addEventListener("DOMContentLoaded",start,{once:true}):start();[0,250,600,1200,2500,5000].forEach(ms=>setTimeout(apply,ms));addEventListener("resize",apply);addEventListener("scroll",apply,true)}
installCompactStreamMenuFullPatch();
