const $=(r,s)=>r.querySelector(s),$$=(r,s)=>Array.from(r.querySelectorAll(s));
const esc=s=>String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
const strip=s=>String(s||"").normalize("NFD").replace(/[\u0591-\u05C7]/g,"");
const idle=()=>new Promise(r=>(window.requestIdleCallback?requestIdleCallback(r,{timeout:80}):setTimeout(r,0)));
const lvl=v=>Number(v)===2?2:1;
const DEF="^(?:#{1,6}\\s+|פרק\\s+|שער\\s+|פרשה\\s+).+";
const STYLE_MAP=[
"p[style-name='Heading 1'] => h1:fresh","p[style-name='heading 1'] => h1:fresh","p[style-name='כותרת 1'] => h1:fresh","p[style-name='כותרת1'] => h1:fresh","p[style-name='1'] => h1:fresh",
"p[style-name='Heading 2'] => h2:fresh","p[style-name='heading 2'] => h2:fresh","p[style-name='כותרת 2'] => h2:fresh","p[style-name='כותרת2'] => h2:fresh","p[style-name='2'] => h2:fresh"];
function clean(h){try{const d=new DOMParser().parseFromString(String(h||""),"text/html");d.querySelectorAll("script,style,iframe,object,embed,link,meta").forEach(n=>n.remove());d.body.querySelectorAll("*").forEach(n=>[...n.attributes].forEach(a=>{/^on/i.test(a.name)&&n.removeAttribute(a.name)}));return d.body.innerHTML||""}catch{return String(h||"")}}
function htmlText(h){try{return new DOMParser().parseFromString(String(h||""),"text/html").body.textContent||""}catch{return String(h||"").replace(/<[^>]*>/g," ")}}
function textHtml(t){return String(t||"").split(/\n{2,}/).map(p=>`<p>${esc(p).replace(/\n/g,"<br>")}</p>`).join("\n")||"<p></p>"}
function editor(pm){return pm?.getActiveEditor?.()||pm?.getActivePane?.()?.editor||pm?.getMainPane?.()?.editor||null}
function setEditor(pm,html){const e=editor(pm);if(!e?.commands?.setContent)throw Error("לא נמצא עורך פעיל");e.commands.setContent(clean(html)||"<p></p>");e.commands.focus?.()}
function progress(u,n,t,c=""){n=Math.max(0,Math.min(100,Math.round(n||0)));u.bar.style.width=n+"%";u.p.textContent=n+"%";u.t.textContent=t||u.t.textContent;u.c.textContent=c}
function attr(n,a){return n?.getAttribute("w:"+a)||n?.getAttribute(a)||n?.getAttributeNS("http://schemas.openxmlformats.org/wordprocessingml/2006/main",a)||""}
function first(r,n){return r?.getElementsByTagNameNS("*",n)[0]||null}
function txt(p){return $$(p,"t").map(n=>n.textContent||"").join("")}
function styleLvl(id,styles){id=String(id||"").trim();const s=styles[id]||{},name=strip(s.name||"");if(s.outline==="0")return 1;if(s.outline==="1")return 2;if(id==="1"||/^(?:Heading)?1$/i.test(id)||/heading\s*1/i.test(name)||/כותרת\s*1/u.test(name))return 1;if(id==="2"||/^(?:Heading)?2$/i.test(id)||/heading\s*2/i.test(name)||/כותרת\s*2/u.test(name))return 2;return null}
async function readFile(f,mode,u){return new Promise((res,rej)=>{const r=new FileReader;r.onerror=()=>rej(r.error||Error("שגיאה בקריאת קובץ"));r.onprogress=e=>{if(e.lengthComputable)progress(u,4+e.loaded/e.total*28,"קורא קובץ",Math.round(e.loaded/e.total*100)+"%")};r.onload=()=>res(r.result);mode==="buf"?r.readAsArrayBuffer(f):r.readAsText(f)})}
async function splitDocx(buf,L,u){const {default:JSZip}=await import("jszip");progress(u,38,"בודק כותרות Word","styleId / outlineLvl");const z=await JSZip.loadAsync(buf),dx=await z.file("word/document.xml")?.async("text");if(!dx)return null;const sx=await z.file("word/styles.xml")?.async("text"),p=new DOMParser,styles={};if(sx){const sd=p.parseFromString(sx,"application/xml");$$(sd,"style").forEach(s=>{const id=attr(s,"styleId");if(id)styles[id]={name:attr(first(s,"name"),"val"),outline:attr(first(s,"outlineLvl"),"val")}})}const d=p.parseFromString(dx,"application/xml"),paras=$$(d,"p").map(x=>{const pr=first(x,"pPr"),sid=attr(first(pr||x,"pStyle"),"val"),ol=attr(first(pr||x,"outlineLvl"),"val");return{text:txt(x).trim(),level:ol==="0"?1:ol==="1"?2:styleLvl(sid,styles)}}),target=lvl(L),chs=[];let cur=null;const close=e=>{if(cur){cur.e=e;cur.i=chs.length;chs.push(cur)}cur=null};for(let i=0;i<paras.length;i+=300){const end=Math.min(i+300,paras.length);for(let j=i;j<end;j++){const x=paras[j];if(!x.text)continue;if(x.level===target){close(j);cur={title:x.text,s:j,e:j+1,len:x.text.length,prev:x.text.slice(0,220)}}else if(cur){cur.e=j+1;cur.len+=x.text.length+1;if(cur.prev.length<220)cur.prev=(cur.prev+"\n"+x.text).slice(0,220)}}progress(u,45+end/Math.max(1,paras.length)*35,"מזהה כותרות DOCX",end.toLocaleString("he-IL")+" פסקאות");await idle()}close(paras.length);if(!chs.length)return null;return{chapters:chs,html:c=>paras.slice(c.s,c.e).map((p,i)=>!p.text?"":i?`<p>${esc(p.text)}</p>`:`<h${target}>${esc(p.text)}</h${target}>`).join("\n")}}
async function splitHtml(html,L,u){const d=new DOMParser().parseFromString(clean(html),"text/html"),target=lvl(L),heads=$$(d.body,`h${target}`),chs=[];if(!heads.length)return null;for(let i=0;i<heads.length;i++){const h=heads[i],n=heads[i+1]||null,r=d.createRange(),w=document.createElement("div");r.setStartBefore(h);n?r.setEndBefore(n):r.setEndAfter(d.body.lastChild||h);w.appendChild(r.cloneContents());const tx=htmlText(w.innerHTML).trim();if(tx)chs.push({title:h.textContent.trim()||`פרק ${i+1}`,html:w.innerHTML,len:tx.length,prev:tx.slice(0,220)});if(i%50===0){progress(u,55+i/Math.max(1,heads.length)*30,"מזהה H"+target,chs.length+" פרקים");await idle()}}return{chapters:chs,html:c=>c.html}}
async function splitText(text,L,u,pat=DEF){const lines=String(text||"").replace(/\r\n/g,"\n").split("\n"),target=lvl(L),md=new RegExp(`^\\s*#{${target}}\\s+.+`,"u"),has=lines.some(l=>md.test(l.trim())),fb=l=>new RegExp(pat||DEF,"u").test(l)||/^(?:פרק|שער|פרשה)\s+\S/u.test(strip(l)),chs=[];let cur=null;const close=e=>{if(cur){cur.e=e;cur.i=chs.length;chs.push(cur)}cur=null};for(let i=0;i<lines.length;i++){const l=lines[i],t=l.trim(),head=has?md.test(t):fb(t);if(head){close(i);cur={title:strip(t).replace(/^#{1,6}\s*/,"").replace(/^(?:פרק|שער|פרשה)\s+/u,"")||`פרק ${chs.length+1}`,s:i,e:i+1,len:l.length,prev:l.slice(0,220)}}else if(cur){cur.e=i+1;cur.len+=l.length+1;if(cur.prev.length<220)cur.prev=(cur.prev+"\n"+l).slice(0,220)}if(i%600===0){progress(u,55+i/Math.max(1,lines.length)*30,"סורק טקסט",i.toLocaleString("he-IL")+" שורות");await idle()}}close(lines.length);return{chapters:chs,html:c=>textHtml(lines.slice(c.s,c.e).join("\n"))}}
async function build(file,L,u,pat){const name=String(file.name||"").toLowerCase();if(name.endsWith(".docx")){const buf=await readFile(file,"buf",u),m=await splitDocx(buf,L,u);if(m)return m;const mammoth=await import("mammoth/mammoth.browser"),r=await mammoth.convertToHtml({arrayBuffer:buf},{styleMap:STYLE_MAP,includeDefaultStyleMap:true});return await splitHtml(r.value,L,u)||{chapters:[],html:()=>""}}const raw=await readFile(file,"txt",u);return /\.(html|htm)$/i.test(name)||/<h[12]\b/i.test(raw)?await splitHtml(raw,L,u)||{chapters:[],html:()=>""}:await splitText(raw,L,u,pat)}
function styles(){if($("#chapter-splitter-lite-style"))return;const s=document.createElement("style");s.id="chapter-splitter-lite-style";s.textContent=`
.chapter-splitter-overlay,.book-choice-overlay{position:fixed;inset:0;z-index:2147483000;background:rgba(0,0,0,.55);display:flex;align-items:center;justify-content:center;direction:rtl;padding:18px}
.chapter-splitter-modal,.book-choice{width:min(900px,96vw);max-height:92vh;overflow:auto;background:#fff;color:#111827;border-radius:24px;box-shadow:0 30px 90px #0006}
.chapter-splitter-head,.book-choice header{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:18px 20px;background:linear-gradient(135deg,#111827,#4338ca,#7e22ce);color:white}
.chapter-splitter-body{display:grid;grid-template-columns:310px 1fr;gap:14px;padding:16px}.chapter-splitter-controls{display:grid;gap:10px}
.chapter-splitter-controls button,.chapter-splitter-controls label,.chapter-splitter-import,.book-choice button,#chapter-splitter-btn{border:0;border-radius:14px;padding:10px 13px;font-weight:800;cursor:pointer;background:#eef2ff;color:#1e1b4b}
.chapter-splitter-file input{display:none}.chapter-splitter-controls select,.chapter-splitter-controls input{width:100%;box-sizing:border-box;border:1px solid #d1d5db;border-radius:12px;padding:9px}
.chapter-progress{padding:12px;border-radius:18px;background:linear-gradient(135deg,#0f172a,#4338ca,#7e22ce);color:white}.chapter-progress-top{display:flex;justify-content:space-between;font-weight:900}.chapter-track{height:14px;background:#fff3;border-radius:99px;overflow:hidden;margin:8px 0}.chapter-bar{height:100%;width:0;background:linear-gradient(90deg,#22d3ee,#a78bfa,#facc15);transition:width .2s}
.chapter-list{max-height:560px;overflow:auto;display:grid;gap:10px}.chapter-item{border:1px solid #e5e7eb;border-radius:18px;padding:12px;background:white}.chapter-item p{margin:6px 0;color:#475569}.chapter-count{font-weight:900;margin-bottom:10px}
.book-choice{width:min(520px,94vw)}.book-choice main{padding:18px}.book-choice-actions{display:grid;gap:10px}.book-book{background:linear-gradient(90deg,#22d3ee,#a78bfa,#facc15)!important;color:#111827!important}.book-regulary{background:#f3f4f6!important}
@media(max-width:760px){.chapter-splitter-body{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function openSplitter(pm){if($("#chapter-splitter-overlay"))return;styles();const o=document.createElement("div");o.id="chapter-splitter-overlay";o.className="chapter-splitter-overlay";o.innerHTML=`<section class="chapter-splitter-modal"><header class="chapter-splitter-head"><div><h2>ייבוא ספר לפני כותרות</h2><div>זיכרון פרקים: הספר נסרק, ורק פרק אחד נטען לעורך בכל פעם.</div></div><button class="chapter-close">×</button></header><div class="chapter-splitter-body"><aside class="chapter-splitter-controls"><label class="chapter-splitter-file">בחר DOCX / TXT / HTML<input type="file" accept=".docx,.txt,.md,.html,.htm"></label><label>חלוקה לפי<select class="chapter-level"><option value="1">H1 / כותרת ראשית</option><option value="2">H2 / כותרת משנית</option></select></label><label>סימון חלופי<input class="chapter-pattern" dir="ltr" value="${esc(DEF)}"></label><div class="chapter-progress"><div class="chapter-progress-top"><span class="chapter-title">ממתין לספר</span><span class="chapter-percent">0%</span></div><div class="chapter-track"><div class="chapter-bar"></div></div><div class="chapter-caption">בחר קובץ כדי להתחיל.</div></div><button class="chapter-first">ייבא פרק ראשון</button></aside><main><div class="chapter-count">אין עדיין פרקים בזיכרון.</div><div class="chapter-list"></div></main></div></section>`;document.body.appendChild(o);const u={bar:$(".chapter-bar",o),p:$(".chapter-percent",o),t:$(".chapter-title",o),c:$(".chapter-caption",o)},list=$(".chapter-list",o),count=$(".chapter-count",o),file=$(".chapter-splitter-file input",o),lev=$(".chapter-level",o),pat=$(".chapter-pattern",o);let mem=null,last=null;$(".chapter-close",o).onclick=()=>o.remove();o.onclick=e=>{if(e.target===o)o.remove()};async function scan(){if(!last)return;list.innerHTML="";count.textContent="סורק פרקים...";mem=await build(last,lev.value,u,pat.value);count.textContent=mem.chapters.length?`נמצאו ${mem.chapters.length.toLocaleString("he-IL")} פרקים בזיכרון.`:"לא נמצאו כותרות בפרק/מסמך.";list.innerHTML=mem.chapters.map((c,i)=>`<article class="chapter-item"><strong>${esc(c.title||`פרק ${i+1}`)}</strong><p>${esc(c.prev||"")}</p><button class="chapter-splitter-import" data-i="${i}">ייבא פרק זה</button></article>`).join("");progress(u,100,mem.chapters.length?"זיכרון מוכן ✓":"לא נמצאו פרקים",mem.chapters.length?"בחר פרק לטעינה עצלה.":"נסה H1/H2 אחר.")}file.onchange=async e=>{last=e.target.files?.[0];if(last)await scan()};lev.onchange=scan;pat.onchange=scan;list.onclick=e=>{const b=e.target.closest(".chapter-splitter-import");if(!b||!mem)return;const c=mem.chapters[Number(b.dataset.i)];if(c){setEditor(pm,mem.html(c));progress(u,100,"הפרק נטען לעורך ✓",c.title||"")}};$(".chapter-first",o).onclick=()=>$(".chapter-splitter-import",list)?.click()}
function choice(pm,btn){if($("#book-choice-overlay"))return;styles();const o=document.createElement("div");o.id="book-choice-overlay";o.className="book-choice-overlay";o.innerHTML=`<section class="book-choice"><header><h3>איך לייבא?</h3><button class="book-close">×</button></header><main><p>לספר עם כותרות Word / H1 / H2 בחר “ייבוא ספר”. למסמך הערות עם זרמים בחר ייבוא רגיל.</p><div class="book-choice-actions"><button class="book-book">ייבוא ספר לפי כותרות</button><button class="book-regular">ייבוא רגיל / זרמי הערות</button></div></main></section>`;document.body.appendChild(o);const close=()=>o.remove();$(".book-close",o).onclick=close;o.onclick=e=>{if(e.target===o)close()};$(".book-book",o).onclick=()=>{close();openSplitter(pm)};$(".book-regular",o).onclick=()=>{close();window.__ravtextAllowRegularWordImport=true;setTimeout(()=>{try{btn.click()}finally{setTimeout(()=>window.__ravtextAllowRegularWordImport=false,0)}},0)}}
function routeWordImport(pm){if(document.__bookImportRouter)return;document.__bookImportRouter=true;document.addEventListener("click",e=>{const b=e.target.closest?.("button[data-cmd='word-import'],button[data-cmd='word-import-streams']");if(!b||window.__ravtextAllowRegularWordImport)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();choice(pm,b)},true)}
function addButton(pm){if($("#chapter-splitter-btn"))return true;const b=document.createElement("button");b.id="chapter-splitter-btn";b.type="button";b.textContent="ייבוא ספר";b.title="ייבוא ספר לפי כותרות Word / H1 / H2";b.onclick=()=>openSplitter(pm);const wb=document.querySelector("button[data-cmd='word-import-streams']")||document.querySelector("button[data-cmd='word-import']");if(wb?.parentElement){const g=document.createElement("span");g.className="tb-group";g.dataset.title="ייבוא ספר";g.appendChild(b);wb.parentElement.insertAdjacentElement("afterend",g);return true}const tb=document.querySelector(".layout-extra-toolbar,.insert-toolbar,[data-ribbon-tab='insert'],.main-toolbar,.toolbar,.ribbon-toolbar,.tools-bar");if(!tb)return false;const g=document.createElement("span");g.className="tb-group";g.appendChild(b);tb.appendChild(g);return true}
export function wireChapterSplitter(paneManager){if(typeof document==="undefined")return;routeWordImport(paneManager);[0,300,1000,2200].forEach(ms=>setTimeout(()=>addButton(paneManager),ms));window.ravtextOpenBookImport=()=>openSplitter(paneManager)}
