const A="data-rav-help-attached",S="data-rav-help-skip",D="rav-help-dot",W="rav-help-wrap",C="rav-help-card",Q="button[data-cmd],button[id],select[id],input[id]:not([type='hidden'])";
const H={
bold:["מודגש","הדגשה לטקסט המסומן."],italic:["נטוי","הטיית הטקסט המסומן."],underline:["קו תחתון","קו תחתון לטקסט המסומן."],strike:["קו מחיקה","קו מחיקה לטקסט המסומן."],
rtl:["ימין לשמאל","כיוון כתיבה עברי לפסקה."],ltr:["שמאל לימין","כיוון כתיבה לועזי לפסקה."],"align-right":["יישור ימין","יישור הפסקה לימין."],"align-center":["מרכוז","מרכוז הפסקה."],"align-left":["יישור שמאל","יישור הפסקה לשמאל."],
bullet:["תבליטים","הפיכת הפסקה לרשימת תבליטים."],ordered:["מספור","הפיכת הפסקה לרשימה ממוספרת."],
link:["קישור","חיבור הטקסט המסומן לכתובת."],unlink:["הסרת קישור","מחיקת הקישור בלי למחוק טקסט."],clear:["ניקוי עיצוב","הסרת עיצוב מהבחירה."],undo:["ביטול","חזרה צעד אחד אחורה."],redo:["שחזור","החזרת פעולה שבוטלה."],
"engine-render":["רינדור עמודים","בניית העמודים מחדש לפי הטקסט וההגדרות."],"word-import-streams":["ייבוא Word מלא","טעינת Word עם זרמי מידע לעימוד."],"word-export":["שמירה ל־Word","ייצוא המסמך לקובץ Word."],"styles-io":["סגנונות","ייצוא או ייבוא סגנונות בין מסמכים."],"round-trip":["בדיקת שמירה","שמירה וטעינה חוזרת לבדיקת תקינות."],"diag-toggle":["אבחון","פתיחה או סגירה של חלונית האבחון."],
"pane-add":["הוספת חלונית","יצירת חלונית עריכה נוספת."],"pane-remove":["הסרת חלונית","מחיקת חלונית העריכה הפעילה."],"split-to-panes":["פיצול לחלוניות","חלוקת טקסט לפי סימוני ‎@NN‎."],"split-special-notes":["הפרדת הערות","העברת הערות מיוחדות לזרם נפרד."],"merge-toggle":["מיזוג או פירוק","מעבר בין חלוניות נפרדות למסמך מאוחד."],"merge-from-panes":["איחוד","איחוד תוכן החלוניות לחלונית הראשית."],"preview-toggle":["תצוגה","מעבר בין עריכה לתצוגת קריאה."],"sync-toggle":["גלילה","סנכרון גלילה בין העריכה לפלט."],"pane-layout-toggle":["פריסת זרמים","שינוי תצוגת הזרמים לרוחב או לגובה."],"lines-toggle":["שורות","הצגה או הסתרה של הפרדת שורות."],
"insert-table":["טבלה","הכנסת טבלה למסמך."],"insert-toc":["תוכן עניינים","הכנסת אזור תוכן עניינים."],"insert-math":["נוסחה","הכנסת נוסחה למסמך."],"insert-comment":["הערה","הוספת הערה במקום הבחירה."],"theme-toggle":["מצב תצוגה","מעבר בין מצב בהיר לכהה."],"lang-toggle":["שפה","החלפת שפת הממשק."]
};
const I={"btn-render":H["engine-render"],"btn-jump-stream":["קפיצה לזרם","מעבר לזרם האחרון שנערך."],"local-font-select":["גופן","בחירת גופן לתצוגה."],"size-selected-select":["גודל","שינוי גודל הטקסט המסומן."],"pdf-zoom-select":["זום","הגדלת או הקטנת חלון התצוגה."],"word-file-input":["קובץ Word","בחירת קובץ לייבוא."]};
const T=new Map([["רנדר",H["engine-render"]],["ייבוא Word עם זרמים מלאים",H["word-import-streams"]],["שמור ל-Word",H["word-export"]],["ייצוא / ייבוא",H["styles-io"]],["JSON round-trip",H["round-trip"]],["אבחון",H["diag-toggle"]],["+ חלונית",H["pane-add"]],["✔ הסר חלונית",H["pane-remove"]],["✂ פצל לחלוניות",H["split-to-panes"]],["✂ הפרד הערות",H["split-special-notes"]],["מזג / פרק",H["merge-toggle"]],["↺ אחד",H["merge-from-panes"]],["תצוגה",H["preview-toggle"]],["גלילה",H["sync-toggle"]],["▥ זרמים לרוחב",H["pane-layout-toggle"]],["☷ שורות",H["lines-toggle"]],["∑ נוסחה",H["insert-math"]],["הערה",H["insert-comment"]],["תוכן עניינים",H["insert-toc"]],["הבנתי",["סגירה","סגירת ההודעה."]]]);
const clean=v=>String(v||"").replace(/\s+/g," ").trim(),name=e=>{let c=e.cloneNode(true);c.querySelectorAll?.(`.${D},.${W},#${C}`).forEach(n=>n.remove());return clean(c.textContent)||clean(e.getAttribute("aria-label"))||clean(e.getAttribute("title"))};
function cmd(c){if(H[c])return H[c];let m=c.match(/^h([1-6])$/);if(m)return[`כותרת ${m[1]}`,`קביעת הפסקה ככותרת ברמה ${m[1]}.`];m=c.match(/^stream-(0[1-8])$/);if(m)return[`זרם ${m[1]}`,`מעבר לעריכת זרם ${m[1]}.`];m=c.match(/^size-(12|15|18|24)$/);if(m)return[`גודל ${m[1]}`,`קביעת גודל ${m[1]}px לטקסט המסומן.`];return null}
function inf(e){let c=e.getAttribute("data-cmd");if(c)return cmd(c);if(e.id&&I[e.id])return I[e.id];return T.get(name(e))||null}
function skip(e){if(!e||e.nodeType!==1||e.hasAttribute(A)||e.getAttribute(S)==="1"||e.disabled||e.hidden)return true;if(e.closest?.(`#${C},.${W},#ribbon-tabs,.profile-menu,.modal-overlay:not(.active)`))return true;if(e.matches?.(".ribbon-tab,.ribbon-collapse-toggle"))return true;if(!inf(e))return true;let s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display==="none"||s.visibility==="hidden"||r.width<8||r.height<8}
function style(){if(document.getElementById("rav-help-style"))return;let s=document.createElement("style");s.id="rav-help-style";s.textContent=`.${W}{display:inline-flex!important;vertical-align:super!important;margin-inline:2px!important;line-height:1!important}.${D}{all:initial!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;width:13px!important;height:13px!important;border-radius:50%!important;border:1px solid #6b93d6!important;background:#fff!important;color:#185abd!important;font:700 9px/1 Arial,sans-serif!important;cursor:help!important;opacity:.75!important;box-shadow:0 1px 2px #0002!important;transform:translateY(-.18em)!important}.${D}:hover,.${D}:focus-visible{opacity:1!important;outline:2px solid #185abd33!important}#${C}{position:fixed;z-index:2147483000;max-width:min(330px,calc(100vw - 24px));background:#fffefa;color:#1f2937;border:1px solid #d8e2f2;border-radius:12px;box-shadow:0 14px 36px #0003;padding:12px 14px;font:13px/1.55 system-ui,Arial,sans-serif;direction:rtl}#${C} h3{margin:0 0 6px;font-size:15px;color:#185abd}#${C} p{margin:0}#${C} button{margin-top:10px;border:1px solid #c8d4e3;background:#f7f9fd;border-radius:999px;padding:4px 10px;cursor:pointer}`;document.head.appendChild(s)}
function close(){document.getElementById(C)?.remove()}function put(p,t,v){let n=document.createElement(t);n.textContent=v;p.appendChild(n);return n}
function open(d,e){let i=inf(e);if(!i)return;close();let c=document.createElement("aside");c.id=C;c.setAttribute("role","dialog");put(c,"h3",i[0]);put(c,"p",i[1]);let b=put(c,"button","סגור");b.type="button";b.onclick=close;document.body.appendChild(c);let r=d.getBoundingClientRect(),p=10,top=r.bottom+7,left=Math.min(Math.max(p,r.left),innerWidth-c.offsetWidth-p);if(top+c.offsetHeight>innerHeight-p)top=Math.max(p,r.top-c.offsetHeight-7);c.style.top=top+"px";c.style.left=left+"px"}
function add(e){if(skip(e))return;let i=inf(e);e.setAttribute(A,"1");let d=document.createElement("span");d.className=D;d.textContent="?";d.title=i[0]+" — "+i[1];d.setAttribute(S,"1");d.setAttribute("role","button");d.setAttribute("tabindex","0");d.setAttribute("aria-label","עזרה: "+i[0]);d.onclick=ev=>{ev.preventDefault();ev.stopPropagation();open(d,e)};d.onkeydown=ev=>{if(ev.key==="Enter"||ev.key===" "){ev.preventDefault();open(d,e)}};let w=document.createElement("span");w.className=W;w.setAttribute(S,"1");w.appendChild(d);try{e.insertAdjacentElement("afterend",w)}catch{e.parentNode?.insertBefore(w,e.nextSibling)}}
function scan(root=document){if(!root.querySelectorAll)return;(root.matches?.(Q)?[root,...root.querySelectorAll(Q)]:[...root.querySelectorAll(Q)]).forEach(add)}
function install(){if(!document.body)return;style();scan();let t=0,sch=r=>{clearTimeout(t);t=setTimeout(()=>scan(r||document),120)};new MutationObserver(ms=>{for(let m of ms)if(m.type==="childList")for(let n of m.addedNodes)n.nodeType===1&&sch(n)}).observe(document.body,{childList:true,subtree:true});document.addEventListener("keydown",e=>{if(e.key==="Escape")close()});document.addEventListener("click",e=>{if(!e.target.closest?.(`#${C},.${D}`))close()},true)}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",install,{once:true}):install();
export{scan as refreshPersonalHelpAssistant};
